name: Update Go Modules with master

on:
  push:
    branches:
      - master

jobs:
  update-go-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'master'
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
      
      - name: Run go get -u
        run: |
          go get -u ./...
          go mod tidy
          gofmt -w .
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update go modules with workflow" || echo "No changes to commit"
          git push origin master
      
      - name: vendor
        run: |
          go mod vendor
      
      - name: Upload vendor directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor-directory
          path: vendor/
          retention-days: 3

      - name: Upload pkg directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod_cache
          path: /home/runner/go/pkg/mod
          retention-days: 3